### ISSUE TITLE
API 23 required?

### ISSUE THREAD

**Issue by jlkalberer** [spark/spark-setup-android#11]
I am not really familiar with android but the only way I could get this to build is by using API 23.  My app was using 19 before.

I get this error if I try to build using 19:
    C:\......\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.0\res\values-v23\values-v23.xml
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

I'm building this in a Cordova app so it could be that.

**Comment by jensck** [comment]
Yes, you'll need to target and compile against API 23.  Your _minimum_ SDK can be as low as 15, though.

Lowering the target SDK isn't on the roadmap, since it's not an easy change(!), and I don't want to make things harder for devs using an up to date, fully native stack, so I'm closing this.
