### ISSUE TITLE
Still showing login screen even when a token is being set manually

### ISSUE THREAD

**Issue by jensck** [spark/spark-setup-android#13]
see: https://community.particle.io/t/two-legged-authentication-android-sdk/18732

**Comment by blackadmin** [comment]
Hi, When can we expect this bug to be fixed, as my company is using this SDK to setup photons and now we are in production. Thank you in advance :).

Regards,
Cloudblocks

**Comment by jensck** [comment]
I'm going to take a stab at fixing this tonight.  If I can't close it tonight, I'll post another update with an ETA.

**Comment by jensck** [comment]
(I'm continuing the convo around this at the community thread linked above; watch that thread for updates until the bug is closed.)

**Comment by jensck** [comment]
@blackadmin calling `ParticleCloud.setAccessToken()` should do it, though some people are obviously running into an issue with this.  Please see the forum post about this; I'm having trouble reproducing this issue and would love any community help in diagnosing just where the trouble is.

**Comment by blackadmin** [comment]
@jensck ok great, will follow and waiting for fix. :)

**Comment by jensck** [comment]
@blackadmin as mentioned on the thread, we could really use help reproducing this issue. Can you try the instructions I give at the end of the thread?

**Comment by blackadmin** [comment]
ok, I will try and let you know.

**Comment by blackadmin** [comment]
@jensck As you said I did and added below code before button listener

`ParticleCloud particleCloud = ParticleCloud.get(this);
        particleCloud.setAccessToken("ACCESS_TOKEN", new Date(1461456951753L));
        System.out.println("Is loggedIn:" + particleCloud.isLoggedIn());`

And it returned me **`false`**

**Comment by javorosas** [comment]
Having the same problem. Any updates on this?

**Comment by jensck** [comment]
v0.3.6 of the device setup lib is out, which (finally) fixes this
