### ISSUE TITLE
Error during device setup

### ISSUE THREAD

**Issue by henrik-d** [spark/spark-setup-android#16]
Hey,

a tester of my app has problems setting up a photon with our app. I got a report showing where the error is occuring. 

![bildschirmfoto 2016-03-08 um 19 37 01](https://cloud.githubusercontent.com/assets/6033679/13612073/e484a88e-e565-11e5-85d8-8287b21dbb26.png)

The tester is using a Samsung Galaxy S4 GT-i9515 running Android 5.0.1
Anything I can do about it?

Best,
henrik

**Comment by jensck** [comment]
Are they using the latest version of the app?

**Comment by henrik-d** [comment]
I'm using Release 0.3.4
Should I update to 0.3.5?

**Comment by jensck** [comment]
Yeah, the latest version had a fix for that issue.

**Comment by henrik-d** [comment]
Great, now it's working. Thanks.
