### ISSUE TITLE
Customization for more than one device

### ISSUE THREAD

**Issue by marcio-granzotto-ckl** [spark/spark-setup-android#19]
So I need to provide the setup screen for 3 different devices, with different names and images.

On iOS' SDK I could just
`[SparkSetupCustomization sharedInstance].deviceName = @"First Device";`
and when I wanted to setup another device
`[SparkSetupCustomization sharedInstance].deviceName = @"Another Device";`

however the same seems not possible with the Android SDK. The docs says that we should create a `customization.xml` file in the values folder and place the customizations in there. But how should I do this with more then one device type?

**Comment by jensck** [comment]
You're correct, this isn't currently possible with the Android SDK.  Enabling this would require some non-trivial refactoring.

**Comment by marcio-granzotto-ckl** [comment]
Ok. As I really need this feature, I will fork the project and try to get this to work. Then I could make a PR with the changes
