### ISSUE TITLE
Change login error handling to match iOS setup lib behavior

### ISSUE THREAD

**Issue by jensck** [spark/spark-setup-android#24]

**Comment by jensck** [comment]
See https://github.com/spark/spark-setup-ios/blob/master/Classes/UI/SparkUserLoginViewController.m#L175

**Comment by CityVibes** [comment]
@jensck Does this still apply? Major difference I see is that we display error through field not an alert.

**Comment by jensck** [comment]
@CityVibes no idea.  You'll have to either review the difference manually or (if you don't have an iDevice) get someone to screenshot the process for you.

**Comment by jensck** [comment]
Or just review the code, if you're confident that's sufficient.  But either way, I can't give a good answer off top if this is still valid.
