### ISSUE TITLE
initWithSetupOnly equivalent

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-setup-android#46]
What is the `initWithSetupOnly` equivalent that is available in iOS sdk?

From:

https://community.particle.io/t/initwithsetuponly-equivalent-for-device-library-in-android-sdk/32952

**Comment by CityVibes** [comment]
@kennethlimcp I think there's no equivalent at the moment, I'll prioritize to either implement and/or document it for upcoming versions.

**Comment by krazineurons** [comment]
Thanks for doing it in on priority folks!

**Comment by idokleinman** [comment]
This is done, except for documentation
