### ISSUE TITLE
connectToApSpinnerDialog Dismisses Too Early

### ISSUE THREAD

**Issue by alvinsee** [spark/spark-setup-android#6]
DiscoverDeviceActivity.java: onPostExecute(SetupStepException error)

hideProgressDiaglog() may dismiss and return back to DiscoverDeviceActivity. Users may re-tap a Particle device on the WiFi fragment list which is undesirable in the setup process. It would be preferable if the progress dialog always dismisses when DiscoverDeviceActivity is destroyed.

**Comment by chobberoni** [comment]
@alvinsee I've tested this and yes, this is a real issue. It is sort of a lag during that process and most users will be impatient (with reason) and try to click the button again.. causing errors. I believe @idokleinman is and already has been looking into this issue. What specific version of android are you using?

**Comment by alvinsee** [comment]
@chobberoni I've tested and replicated the issue on both Android Lollipop and Marshmallow Preview 3.

**Comment by jensck** [comment]
I'm able to reproduce this -- I'll add this to the bug queue for an upcoming release.

**Comment by alvinsee** [comment]
@jensck much appreciated!

**Comment by mhespenh** [comment]
Just FYI- still exists on 0.3.0- I'm going to dig into the code tomorrow to see if there I can find a fix in the meantime, I'll report back if I find one.

**Comment by chobberoni** [comment]
@jensck any update on this? we have a client who is going into production run of their platform and need this bug fixed

**Comment by jensck** [comment]
@chobberoni I looked at it last night and I believe I found the cause; I'm going to implement and test the fix tonight.

**Comment by chobberoni** [comment]
thanks @jensck !!! :+1: :smile:

**Comment by kneuron** [comment]
woo! Thanks, all!
