### ISSUE TITLE
SDK attempts to set claim code on unclaimed devices in `setupOnly` mode

### ISSUE THREAD

**Issue by brahma-dev** [spark/spark-setup-android#69]
This seems to be the offending code. 
https://github.com/particle-iot/spark-setup-android/blob/master/devicesetup/src/main/java/io/particle/android/sdk/devicesetup/ui/DiscoverProcessWorker.java#L84

When `c=0` it attempts to set `null` as claim code which crashes the app ([here](https://github.com/particle-iot/spark-setup-android/blob/ea1d25b33125416a2fc3d7e8e13bf84d3be133ab/devicesetup/src/main/java/io/particle/android/sdk/devicesetup/commands/SetCommand.java#L18)). I believe this is unintended behaviour because older versions of stock exampleapp (in `initWithSetupOnly` mode) still work for me.

**Comment by jensck** [comment]
Thanks for the heads up! I'll look at this sometime this week.
