### ISSUE TITLE
com.afollestad:material-dialogs:0.7.8.0

### ISSUE THREAD

**Issue by dardenhome** [spark/spark-setup-android#8]
I just pulled the most recent code. I tried building and I get this message:

> Could not resolve all dependencies for configuration ':devicesetup:_debugCompile'.
   > Could not find com.afollestad:material-dialogs:0.7.8.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.pom
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.jar
         file:/Users/jdarden/Library/Android/sdk/extras/android/m2repository/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.pom
         file:/Users/jdarden/Library/Android/sdk/extras/android/m2repository/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.jar
         file:/Users/jdarden/Library/Android/sdk/extras/google/m2repository/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.pom
         file:/Users/jdarden/Library/Android/sdk/extras/google/m2repository/com/afollestad/material-dialogs/0.7.8.0/material-dialogs-0.7.8.0.jar

Are we missing a depot? Or maybe the author moved/removed this version of material-dialogs?

**Comment by dardenhome** [comment]
UPDATE: it looks like adding com.afollestad:material-dialogs:0.7.8.1 gets me through the build error.

**Comment by jensck** [comment]
The 0.3.0 release addresses this, too.  Thanks for the report!

**Comment by philipmeier** [comment]
@jensck I am getting this for 'com.afollestad:material-dialogs:0.7.9.1' -- found on the head of the code as of Dec 9th. (a7402b8 == devicesetup:0.3.2)

Apologies for posting on a closed ticket but it seems related. Let me know if you want me to open a new ticket instead.

In the build.gradle I find:
    compile 'com.afollestad:material-dialogs:0.7.9.1'

Does this repository work as-is for other people?
Is there soemthing like "maven { url "https://jitpack.io" }" missing?

**Comment by philipmeier** [comment]
I am currently trying:

    compile('com.github.afollestad.material-dialogs:core:0.7.9.1@aar') {
        transitive = true
    }

**Comment by philipmeier** [comment]
Ultimately the above worked, but I also had to make sure my root build.gradle file had:

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
