### ISSUE TITLE
NPE in LoginActivity (after upgrading to 0.3.0 from 0.2.0...?)

### ISSUE THREAD

**Issue by sbose78** [spark/spark-setup-android#9]
On calling : 
ParticleDeviceSetupLibrary.startDeviceSetup(Activity.this);

Below is the stacktrace :

94): getRunningAppProcesses: caller 10390 does not hold REAL_GET_TASKS; limiting output
E/AndroidRuntime(16937): FATAL EXCEPTION: main
E/AndroidRuntime(16937): Process: com.greenopia.android, PID: 16937
E/AndroidRuntime(16937): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.greenopia.android/io.particle.android.sdk.accountsetup.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.particle.android.sdk.utils.ui.SoftKeyboardVisibilityDetectingLinearLayout.setOnSoftKeyboardVisibilityChangeListener(io.particle.android.sdk.utils.ui.SoftKeyboardVisibilityDetectingLinearLayout$SoftKeyboardVisibilityChangeListener)' on a null object reference
E/AndroidRuntime(16937):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(16937):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(16937):     at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(16937):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(16937):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16937):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(16937):     at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(16937):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16937):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(16937):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(16937):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jensck** [comment]
Updating the title: the permission referenced is from another app, but there is a real bug here in the form of an NPE.

**Comment by jensck** [comment]
Does the device where you're hitting this have a hardware keyboard by any chance...?

**Comment by sbose78** [comment]
No @jensck .
It's an Android device without an external keyboard.

**Comment by jensck** [comment]
What else can you tell me about this, e.g.:
- device make and model
- version of Android
- is this a custom ROM?
- which software keyboard it's using
- what are the steps to reproduce?  Do those steps work on a fresh install?
- do you have developer options set like destroying activities as soon as you exit them?

**Comment by jensck** [comment]
Also, none of the code being referred to by that stack trace seems to have changed from 0.2.0 to 0.3.0 -- it seems odd that the upgrade would cause it.  Can you try downgrading and see if you can still reproduce it?

**Comment by jensck** [comment]
Closing this; please feel free to re-open if you are still running into this issue and can provide some of the info above!
